[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  GIT_LFS_ENABLED = "false"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
